name: tmom
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - comm=0.2.3
  - cpython=3.13.11
  - debugpy=1.8.19
  - decorator=5.2.1
  - executing=2.2.1
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.13.11
  - python-dateutil=2.9.0.post0
  - python-gil=3.13.11
  - python_abi=3.13
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alpaca-py==0.43.2
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - build==1.3.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - dotenv==0.9.9
      - fastapi==0.134.0
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - markupsafe==3.0.3
      - mistune==3.2.0
      - msgpack==1.1.2
      - multidict==6.7.1
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - numpy==2.4.0
      - openai==2.15.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - prometheus-client==0.24.1
      - propcache==0.4.1
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyproject-hooks==1.2.0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - send2trash==2.1.0
      - sniffio==1.3.1
      - soupsieve==2.8.3
      - sseclient-py==1.9.0
      - starlette==0.52.1
      - ta-lib==0.6.8
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - uvicorn==0.41.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==16.0
      - widgetsnbextension==4.0.15
      - yarl==1.22.0
prefix: /Users/akotta/miniconda3/envs/tmom
